[package]
name = "tech-demand-matching"
version = "2.3.1"
description = "AI技术经理人"
authors = ["Guoyf888"]
edition = "2021"

[lib]
name = "tech_demand_matching"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_os = "android"))'.dependencies]
keyring = "2.3"
